import os


consoles = {
    'nes': {
        'name': 'Nintendo Entertainment System',
        'players_number': 2,
        'controls': [
            ("up", "Up"),
            ("down", "Down"),
            ("left", "Left"),
            ("right", "Right"),
            ("a", "A"),
            ("b", "B"),
            ("select", "Select"),
            ("start", "Start"),
        ],
        'exec': [
            'sudo', '-u', 'meldnafen', 'retroarch', '-v',
            '-s', os.path.expanduser('~/save'),
            '-S', os.path.expanduser('~/save'),
            '-L', '/usr/lib/libretro/quicknes_libretro.so',
        ],
        'exclude': '*.ips',
    },
    'pce': {
        'name': 'PC Engine & SuperGrafx',
        'players_number': 2,
        'controls': [
            ("up", "Up"),
            ("down", "Down"),
            ("left", "Left"),
            ("right", "Right"),
            ("a", "I"),
            ("b", "II"),
            ("select", "Select"),
            ("start", "Run"),
        ],
        'exec': [
            'sudo', '-u', 'meldnafen', 'retroarch', '-v',
            '-s', os.path.expanduser('~/save'),
            '-S', os.path.expanduser('~/save'),
            '-L', '/usr/lib/libretro/mednafen_supergrafx_libretro.so',
        ],
        'exclude': 'syscard3.pce;*.bin',
    },
    'snes': {
        'name': 'Super Nintendo',
        'players_number': 2,
        'controls': [
            ("up", "Up"),
            ("down", "Down"),
            ("left", "Left"),
            ("right", "Right"),
            ("a", "A"),
            ("b", "B"),
            ("x", "X"),
            ("y", "Y"),
            ("l", "L"),
            ("r", "R"),
            ("select", "Select"),
            ("start", "Start"),
        ],
        'exec': [
            'sudo', '-u', 'meldnafen', 'retroarch', '-v',
            '-s', os.path.expanduser('~/save'),
            '-S', os.path.expanduser('~/save'),
            '-L', '/usr/lib/libretro/snes9x_next_libretro.so',
        ],
    },
    'md': {
        'name': 'Mega Drive / Genesis',
        'players_number': 4,
        'controls': [
            ("up", "Up"),
            ("down", "Down"),
            ("left", "Left"),
            ("right", "Right"),
            ("y", "A"),
            ("b", "B"),
            ("a", "C"),
            ("l", "X"),
            ("x", "Y"),
            ("r", "Z"),
            ("start", "Start"),
        ],
        'exec': [
            'sudo', '-u', 'meldnafen', 'retroarch', '-v',
            '-s', os.path.expanduser('~/save'),
            '-S', os.path.expanduser('~/save'),
            '-L', '/usr/lib/libretro/genesis_plus_gx_libretro.so',
        ],
    },
    'psx': {
        'name': 'PlayStation',
        'players_number': 8,
        'controls': [
            ("up", "Up"),
            ("down", "Down"),
            ("left", "Left"),
            ("right", "Right"),
            ("a", "Circle"),
            ("b", "Cross"),
            ("x", "Triangle"),
            ("y", "Square"),
            ("l", "L1"),
            ("r", "R1"),
            ("l2", "L2"),
            ("r2", "R2"),
            ("select", "Select"),
            ("start", "Start"),
        ],
        'exec': [
            'sudo', '-u', 'meldnafen', 'retroarch', '-v',
            '-s', os.path.expanduser('~/save'),
            '-S', os.path.expanduser('~/save'),
            '-L', '/usr/lib/libretro/pcsx_rearmed_libretro.so',
        ],
        'exclude': '*.bin',
    },
}
